### ISSUE TITLE
Problem in code

### ISSUE THREAD

**Issue by Eisverygoodletter** [Eisverygoodletter/roboticsclub#5]
https://github.com/Eisverygoodletter/roboticsclub/blob/f9d04c8ce30748b1d0489fecd3b816fa3ebad177/alex/alex.ino#L25

@txvvgnx 
Your code has a problem
how is the robot supposed to know what to do if it went in a dead end and there's a wall in front of it, it would just get stuck and die. Also start turn turns both wheels at once, so you can't start turning as soon as you detect there being space on the left

**Comment by txvvgnx** [comment]
no

**Comment by txvvgnx** [comment]
what is wrong with void loop()
i see nothing wrong

**Comment by Eisverygoodletter** [comment]
check the function pls
